/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv worker/env.d.ts` (hash: acfd7fe58b467aaf05f9ffe3390a809c)
interface __BaseEnv_CloudflareEnv {
	PHOTOS: R2Bucket;
	DB: D1Database;
	SUPABASE_URL: "https://nfxzluqlprkelwociuaa.supabase.co";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL">> {}
}
